basis: def2-TZVPP
basis_atom: null
ecp_atom: {yb: ecp-28-mwb}
charge: null
coord_file: coord
desy: false
desy_eps: null
ex_all_states: null
ex_exopt: null
ex_frequency: null
ex_frequency_unit: null
ex_irrep_states: null
ex_method: null
ex_mp2: null
ex_multi: null
functional: tpss
gridsize: m4
ired: false
marij: true
maxcor: null
maxiter: null
method: dft
metric: null
mp2energy: false
usemo: null
ri: true
rijk: false
scfconv: 6
scfiterlimit: 400
sym: c1
sym_eps: null
title: ridft
turbobin: null
unpaired_electrons: null
use_f12: false
use_f12*: null
copymo: null
use_cosmo: true
epsilon: 7.58